### PR TITLE
OPENAI_ENDPOINT support

### PR DESCRIPTION
**Pull request by Slahser**

### CODE REVIEW

**Comment by Slahser** [comment]
#16

**Comment by danenania** [comment]
Thank you, this looks good! I'll test and merge tomorrow most likely.

**Review by cyxol — APPROVED** [review]

**Comment by AxDSan** [comment]
Question, what if I add an OpenAI compatible endpoint like from a model provider like OpenRouter @ `https://openrouter.ai/api/v1` and I want to modify or select an alternative/different model to carry out the ops? just adding the endpoint will not be suffice right? will this need to turn into an issue itself?

**Comment by danenania** [comment]
> Question, what if I add an OpenAI compatible endpoint like from a model provider like OpenRouter @ `https://openrouter.ai/api/v1` and I want to modify or select an alternative/different model to carry out the ops? just adding the endpoint will not be suffice right? will this need to turn into an issue itself?

@AxDSan Yes for this purpose I want to allow for adding dynamically configured models to supplement the [default OpenAI models](https://github.com/plandex-ai/plandex/blob/main/app/shared/ai_models.go). These would then integrate with the `plandex models` and `plandex set-model` commands. Apart from the endpoint, I think they would also need to specify an associated environment variable to read the api key from.

But until that's done, I think the `OPENAI_ENDPOINT` in this PR is a good and simple stopgap measure.

**Comment by AxDSan** [comment]
Yup totally understandable, I'd also assume the `OPENAI_API_KEY` environment variable can be interchangeable with the OpenRouter key, but for sake of SOC it would be good to just do what you say instead, which is introducing a way of reading the env var to read the api key from. `OPENROUTER_API_KEY` or something.

**Comment by ErikBjare** [comment]
I saw in #65 that the `OPENAI_API_BASE` was rejected in favor of this `OPENAI_ENDPOINT`.

However, `OPENAI_API_BASE` is the convention used by OpenAI's Python library etc. Ideally it should be the same here, to keep things consistent.

**Comment by danenania** [comment]
Thanks @ErikBjare, I didn't realize that. I'll add support for `OPENAI_API_BASE` in the next release for standardization, and make that the default in the readme/docs, but still keep support for `OPENAI_ENDPOINT` as well to avoid a breaking change for anyone who starts using it in the meantime.

**Pull request merged**
