### PR TITLE
Provide a prebuilt docker image for self-hosting

### PR DESCRIPTION
**Pull request by appreciated**
The PR adds a GitHub Workflow that builds a Docker image and deploys it to the GitHub Container Registry when a GitHub release is published, it fixes more or less #78.

Note, to make it work, the following needs to be configured:
grafik

The available Docker images will then be shown below the releases:
grafik

### CODE REVIEW

**Comment by danenania** [comment]
Thank you! This looks great. I'll get it merged soon and into the next release 👍

**Comment by appreciated** [comment]
@danenania What are your plans on merging this PR?

**Comment by danenania** [comment]
@appreciated I plan to spend some time getting PRs merged (this one included) in the next few days. Thanks!

**Comment by danenania** [comment]
This is merged, but the build is failing... looks like the release tag I'm using isn't valid for a Docker image tag?

CleanShot 2024-06-21 at 10 17 01

**Comment by appreciated** [comment]
@danenania Here is a tested fix to sanitize the version:
```
name: Build and publish Docker Image if a new Github release was created

on:
  release:
    types: [created]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Sanitize ref name
        id: sanitize
        run: echo "SANITIZED_REF_NAME=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app/
          file: ./app/Dockerfile.server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/plandex-server:${{ env.SANITIZED_REF_NAME }}
            ghcr.io/${{ github.repository_owner }}/plandex-server:latest
```

**Comment by danenania** [comment]
I see, could we add a step that bails out if the tag contains `cli` perhaps?

**Comment by appreciated** [comment]
> I see, could we add a step that bails out if the tag contains `cli` perhaps?

Yes we can do this

**Comment by danenania** [comment]
@appreciated  Cool, I'd be happy to merge another PR that fixes this... thank you for your help! 🙏

**Comment by appreciated** [comment]
Gladly 🙂 here comes #153

**Comment by metatrot** [comment]
Hi. I'm not able to get the [Self Hosting instructions](https://docs.plandex.ai/hosting/self-hosting/#quickstart) from the docs working, and keep getting errors similar to this user #169. Having a prebuilt docker image to run the plandex server locally would be great.

**Comment by danenania** [comment]
Hi @metatrot, please see my comment here on that issue: https://github.com/plandex-ai/plandex/issues/169#issuecomment-2253529710

In any case, will look to get the prebuilt image working as well soon.

**Pull request merged**
